package main

import (
	"fmt"
	"io"
	"strings"
)

// Everything below emits shell source. Every value that reaches the output goes
// through one of the quoting helpers rather than being interpolated raw: the
// inputs are command names and summaries from this binary, but a summary is a
// sentence written by a human, and one apostrophe in one summary would end a
// single-quoted string and turn the rest of the line into commands. That is code
// execution in the user's login shell, so the escaping is not cosmetic.

// shellSingleQuote wraps s for POSIX shells and zsh. A single quote inside a
// single-quoted string cannot be backslash-escaped — the only way out is to close
// the string, emit a literal quote, and reopen, so `it's` becomes
//
//	'it'\''s'
//
// (indented because gofmt rewrites a doubled quote in prose as a typographic one).
func shellSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// fishQuote wraps s for fish, which does allow \' inside single quotes and also
// treats a backslash as an escape there — so both have to be escaped, backslash
// first or the added backslashes would themselves be escaped.
func fishQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "'", `\'`)
	return "'" + s + "'"
}

// zshDescribe escapes a description for zsh's `_describe`/`_arguments` syntax,
// where a colon separates the value from its description. An unescaped colon in
// a summary would truncate the description at that point.
func zshDescribe(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, ":", `\:`)
	s = strings.ReplaceAll(s, "[", `\[`)
	s = strings.ReplaceAll(s, "]", `\]`)
	return s
}

func writeBashCompletion(w io.Writer) error {
	var b strings.Builder
	b.WriteString("# bash completion for qeuro. Generated by `qeuro completion bash`.\n")
	b.WriteString("# Install: qeuro completion bash > /etc/bash_completion.d/qeuro\n")
	b.WriteString("#      or: eval \"$(qeuro completion bash)\"\n\n")
	b.WriteString("_qeuro() {\n")
	b.WriteString("    local cur prev cmd\n")
	b.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	b.WriteString("    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	b.WriteString("    cmd=\"\"\n")
	// The first non-flag word after the binary is the subcommand. Scanning for it
	// rather than reading COMP_WORDS[1] keeps `qeuro --help cost` working and, more
	// importantly, does not mistake a flag for a command.
	b.WriteString("    local i\n")
	b.WriteString("    for ((i=1; i < COMP_CWORD; i++)); do\n")
	b.WriteString("        case \"${COMP_WORDS[i]}\" in\n")
	b.WriteString("            -*) ;;\n")
	b.WriteString("            *) cmd=\"${COMP_WORDS[i]}\"; break ;;\n")
	b.WriteString("        esac\n")
	b.WriteString("    done\n\n")

	// A flag that takes a value gets no suggestions at all. Offering the command
	// list after `--budget` would suggest that "logout" is a valid amount.
	b.WriteString("    case \"$prev\" in\n")
	b.WriteString("        " + strings.Join(bashValueFlags(), "|") + ")\n")
	b.WriteString("            return 0 ;;\n")
	b.WriteString("    esac\n\n")

	b.WriteString("    if [ -z \"$cmd\" ]; then\n")
	b.WriteString("        COMPREPLY=( $(compgen -W " + shellSingleQuote(strings.Join(completionNames(), " ")) + " -- \"$cur\") )\n")
	b.WriteString("        return 0\n")
	b.WriteString("    fi\n\n")

	b.WriteString("    local opts=\"\"\n")
	b.WriteString("    case \"$cmd\" in\n")
	specs := completionSpecs()
	for _, name := range sortedKeys(specs) {
		spec := specs[name]
		words := append(append([]string{}, spec.words...), spec.flags...)
		if len(words) == 0 {
			continue
		}
		b.WriteString("        " + strings.Join(dispatchWords(name), "|") + ") opts=" + shellSingleQuote(strings.Join(words, " ")) + " ;;\n")
	}
	b.WriteString("    esac\n")
	b.WriteString("    COMPREPLY=( $(compgen -W \"$opts\" -- \"$cur\") )\n")
	b.WriteString("}\n")
	b.WriteString("complete -F _qeuro qeuro\n")
	_, err := io.WriteString(w, b.String())
	return err
}

// bashValueFlags is the set of flags that consume the next word. Derived from the
// argument parsers, so a flag added there without a value must not appear here.
func bashValueFlags() []string {
	return []string{"--budget", "--since", "--model", "--url"}
}

func writeZshCompletion(w io.Writer) error {
	var b strings.Builder
	b.WriteString("#compdef qeuro\n")
	b.WriteString("# zsh completion for qeuro. Generated by `qeuro completion zsh`.\n")
	b.WriteString("# Install: qeuro completion zsh > \"${fpath[1]}/_qeuro\"\n\n")
	b.WriteString("_qeuro() {\n")
	// state is set by `_arguments -C` and read below. Declared local because a
	// completion function that leaks $state into the shell corrupts the next
	// completion that reads it.
	b.WriteString("    local state\n")
	b.WriteString("    local -a commands\n")
	b.WriteString("    commands=(\n")
	for _, pair := range completionSummaries() {
		b.WriteString("        " + shellSingleQuote(pair[0]+":"+zshDescribe(pair[1])) + "\n")
	}
	b.WriteString("    )\n\n")
	b.WriteString("    _arguments -C '1: :->command' '*:: :->args'\n\n")
	b.WriteString("    case $state in\n")
	b.WriteString("        command)\n")
	b.WriteString("            _describe -t commands 'qeuro command' commands\n")
	b.WriteString("            ;;\n")
	b.WriteString("        args)\n")
	b.WriteString("            case $words[1] in\n")
	specs := completionSpecs()
	for _, name := range sortedKeys(specs) {
		spec := specs[name]
		if len(spec.words) == 0 && len(spec.flags) == 0 {
			continue
		}
		b.WriteString("                " + strings.Join(dispatchWords(name), "|") + ")\n")
		if len(spec.words) > 0 {
			b.WriteString("                    _values 'subcommand' " + quoteAll(spec.words, shellSingleQuote) + "\n")
		}
		if len(spec.flags) > 0 {
			b.WriteString("                    _values 'flag' " + quoteAll(spec.flags, shellSingleQuote) + "\n")
		}
		b.WriteString("                    ;;\n")
	}
	b.WriteString("            esac\n")
	b.WriteString("            ;;\n")
	b.WriteString("    esac\n")
	b.WriteString("}\n")
	// The trailing call is what makes the file work when it is *sourced* rather
	// than installed on fpath — `source <(qeuro completion zsh)` is what people
	// actually put in .zshrc, and with #compdef alone the function would be defined
	// and never bound. When the file is autoloaded from fpath instead, compinit
	// arranges for this same call, so it is correct in both cases.
	b.WriteString("\n_qeuro \"$@\"\n")
	_, err := io.WriteString(w, b.String())
	return err
}

func writeFishCompletion(w io.Writer) error {
	var b strings.Builder
	b.WriteString("# fish completion for qeuro. Generated by `qeuro completion fish`.\n")
	b.WriteString("# Install: qeuro completion fish > ~/.config/fish/completions/qeuro.fish\n\n")
	// -f: no file completion. Every one of these commands takes words or nothing,
	// and a file list mixed into a command list is noise on every Tab.
	for _, pair := range completionSummaries() {
		b.WriteString(fmt.Sprintf("complete -c qeuro -f -n __fish_use_subcommand -a %s -d %s\n",
			fishQuote(pair[0]), fishQuote(pair[1])))
	}
	// Aliases, classified by shape. fish distinguishes a subcommand word from an
	// option, so `auto` is offered with -a while `--version` and `-v` are declared
	// as options — listing a flag as a positional value would complete it in
	// positions where it is not a flag, and hide it where it is.
	b.WriteString("\n")
	for _, c := range commands() {
		for _, alias := range c.aliases {
			switch {
			case strings.HasPrefix(alias, "--"):
				b.WriteString(fmt.Sprintf("complete -c qeuro -f -l %s -d %s\n",
					fishQuote(strings.TrimPrefix(alias, "--")), fishQuote(c.summary)))
			case strings.HasPrefix(alias, "-"):
				b.WriteString(fmt.Sprintf("complete -c qeuro -f -s %s -d %s\n",
					fishQuote(strings.TrimPrefix(alias, "-")), fishQuote(c.summary)))
			default:
				b.WriteString(fmt.Sprintf("complete -c qeuro -f -n __fish_use_subcommand -a %s -d %s\n",
					fishQuote(alias), fishQuote(c.summary)))
			}
		}
	}
	b.WriteString("\n")
	specs := completionSpecs()
	for _, name := range sortedKeys(specs) {
		spec := specs[name]
		// __fish_seen_subcommand_from takes a list, so the aliases go in beside the
		// name and `qeuro auto --budget` completes like `qeuro chat --budget`.
		seen := strings.Join(dispatchWords(name), " ")
		for _, word := range spec.words {
			b.WriteString(fmt.Sprintf("complete -c qeuro -f -n '__fish_seen_subcommand_from %s' -a %s\n",
				seen, fishQuote(word)))
		}
		for _, flag := range spec.flags {
			b.WriteString(fmt.Sprintf("complete -c qeuro -f -n '__fish_seen_subcommand_from %s' -l %s\n",
				seen, fishQuote(strings.TrimPrefix(flag, "--"))))
		}
	}
	_, err := io.WriteString(w, b.String())
	return err
}

func quoteAll(items []string, quote func(string) string) string {
	out := make([]string, 0, len(items))
	for _, it := range items {
		out = append(out, quote(it))
	}
	return strings.Join(out, " ")
}

// sortedKeys (mcp_cmd.go) keeps the generated scripts byte-stable across runs:
// Go randomises map iteration, and a script whose lines shuffle on every
// regeneration is unreviewable in a dotfiles diff.
